### ISSUE TITLE
Set up configuration system

### ISSUE THREAD

**Issue by oyeb** [aviacommerce/avia#20]
# Use cases
1. Configure the payment_method seed data, the `:code`s are currently hardcoded and it will become much simpler to maintain changes to them if they are defined in a single place. [comment](https://github.com/aviabird/snitch/pull/14#pullrequestreview-101070804)

# Format
1. YAML
2. JSON
3. INI

**Comment by kartikjagdale** [comment]
@oyeb assigning it myself.
will tag the PR for it here. :)
