### ISSUE TITLE
Can't "use" snitch

### ISSUE THREAD

**Issue by oyeb** [aviacommerce/avia#25]
### How is Snitch going to be used (or customized)?
Snitch is not a library, it's an app. So our users won't be adding `{:snitch, "> 0.1"}` to their `deps`. They'll have to clone it and _actually edit_ Snitch itself.

### Why is this important?
* `snitch_core` comes with its own `Repo`. :x:
    - Our user must supply _his_ repo to Snitch.
* Snitch must read from config which payment gateway should be used. This configuration cannot lie under `:snitch_core` OTP app.
* This is slightly related to #10, see this [comment](https://github.com/aviabird/snitch/pull/10#issuecomment-368446029)

### Perhaps...
`Snitch` is like a _demo app_ that uses the `snitch_core` library. In that case,
* `snitch_core` should be added as a dependency.
* `snitch_core` must fetch stuff like Repo config, Gateway config from _outside_ the lib.
* `snitch_core` provides some mix tasks to seed the _user's Repo_.
* how should we test `snitch_core` if we do the above?

**Comment by arjun289** [comment]
@oyeb, have you come up with any strategy for this?
