### ISSUE TITLE
Generic type 'NguCarousel<T>' requires 1 type argument(s)

### ISSUE THREAD

**Issue by vg22** [aviacommerce/avia#309]
Hi I am trying to run the application but getting the following error:
```
ERROR in src/app/landing/components/lp-banner/lp-banner.component.ts(14,26): error TS2314: Generic type 'NguCarousel<T>' requires 1 type argument(s).
src/app/product/components/product-detail-page/product-images/product-images.component.ts(55,7): error TS2322: Type 'number' is not assignable to type 'CarouselInterval'.
src/app/product/components/product-detail-page/product-images/product-images.component.ts(56,7): error TS2322: Type '{ visible: boolean; pointStyles:
string; }' is not assignable to type 'boolean'.
src/app/product/components/product-detail-page/product-images/product-images.component.ts(90,7): error TS2322: Type 'true' is not assignable to type 'Touch'.
```
I think it is asking to provide a type to generic, but even if I do so it still throws an error.
I already saw a similar issue here, but no solution provided.  https://github.com/sheikalthaf/ngu-carousel/issues/106
Can anyone please help I am stuck. Apologies if I missed anything, Please let me know if you need any extra information. Thanks.

**Comment by pkrawat1** [comment]
hi, @vg22 I'm working on a fix for that. Try `upgrade-deps` in angularspree for now. You'll need to delete `node_modules` and reinstall using `yarn`

**Comment by pkrawat1** [comment]
Raised a [PR 299](https://github.com/aviabird/angularspree/pull/299) on angularspree
