### ISSUE TITLE
Use attribute map instead of multiple params in model create/update code

### ISSUE THREAD

**Issue by pkrawat1** [aviacommerce/avia#37]
@oyeb gave a suggestion to use create method in models with single `map` type `param` only.
Since the current implementation needs the required number of fields in a schema to be used in create params. 

new suggestion
```
   create(required1, required2, optional\\ %{}), do: ...

OR
   
   create(attributes\\ %{}), do: ...
```

**Comment by oyeb** [comment]
Instead of the `map`, a `keyword` list would be better.
```elixir
create(required1, required2, optional \\ []), do: ...
```
Conventionally, the last arg is `keyword` in Elixir, and it's easier to type.

**Comment by pkrawat1** [comment]
Let's move to only a `map` as params
