### ISSUE TITLE
User has no addresses

### ISSUE THREAD

**Issue by oyeb** [aviacommerce/avia#38]
## Requirement
* Addresses that are "saved" by the user are associated with her. These saved addresses can be used during checkout as billing and/or shipping address.
* A new `Address` record is created if the user does not use a saved address as billing/shipping address during checkout.
* User can edit (or update) saved addresses.
    - What if this address was used in some previous order?
      > Add a new Address record. From the old record remove the association with the user. All orders using the old address will thus remain intact.

## Discussion
1. A foreign_key in Address referencing User that can be `null` should suffice. Or we could make a join table (that would be overkill as `User:Address::1:n`, and not `m:n`).

**Comment by pkrawat1** [comment]
In spree there are 3 types of addresses are there.
`user_address`
`billing_address`
`shipping_address`

**Comment by oyeb** [comment]
AFAICS, there's no `user_address`, only one address table, referenced by:
* user via `bill_address_id`, `ship_address_id`
* order via `bill_address_id`, `ship_address_id`

Are you suggesting we do exactly as Spree does?

**Comment by ashish173** [comment]
```
# Associates the specified user with the order.
def associate_user!(user, override_email = true)
   self.user           = user
   self.email          = user.email if override_email
   self.created_by   ||= user
   self.bill_address ||= user.bill_address.try(:clone)
   self.ship_address ||= user.ship_address.try(:clone)

   changes = slice(:user_id, :email, :created_by_id, :bill_address_id, :ship_address_id)

   # immediately persist the changes we just made, but don't use save
   # since we might have an invalid address associated
   self.class.unscoped.where(id: self).update_all(changes)
end
```
In spree, they are making a copy of the user address(billing, shipping) and then associating that with the order. This is a good approach given users can change(minor) their addresses in future. This should not result in a change in the address associated with an old order.

**To summarise we take the same approach as spree.** 

--------------------------------------

In Rails using `clone` is [not a good idea](https://stackoverflow.com/a/60053/1930053) use `dup` instead.

**Comment by oyeb** [comment]
We have to address two things:
#### Multiple saved addresses or no?
IMO (and also @jyotigautam's -- who suggested it in the first place), Spree's approach to User addresses is very inferior. Spree allows a user to save only two addresses in his profile (billing, shipping). Let's instead let the user save as many address as she wants. 
#### To copy early or update later?
* [copy early] As suggested in the [comment above](https://github.com/aviabird/snitch/issues/38#issuecomment-372980779). Cons: Unnecessary clones of the _same_ address for _many_ orders of a user.
* [update later] As suggested in the issue description. Pros: When the a saved address is edited, one **address record** (old) is updated, another (new) is inserted. **The address associated with an old order is *not updated*, nor are the orders updated**.

**Comment by ashish173** [comment]
Addressing your concerns.

### Multiple addresses

I am in support of user being able to add multiple addresses. There should be no limits on that.

### Associating addresses with orders

Firstly, Order serves as a history(think of it as a report). @pkrawat1 suggested and I agree too that one should not have associations in place for records which are meant for historical purposes or for reporting. In this case, we want to preserve the change in addresses if any. 
I have reviewed @oyeb's suggestion and I think it would be an overkill to take that approach. At the same time, I agree with his suggestions that taking the spree approach would create many clones unnecessary which have database relations I personally think this is not needed.

We had a small discussion and here is what we have agreed posting it for ref.

We still want to have a clone of address(shipping, billing) but that should go inside the `order` relation only but as `json` objects for both address(shipping, billing). We can discuss about how to handle when both the addresses are same and keep a flag to not repeat data. 

Embedding seems like a good solution for it. Refer this [link](https://robots.thoughtbot.com/embedding-elixir-structs-in-ecto-models). 

The tradeoffs with using this approach like not being able to use the DB constraints don't really matter here because the original address in the user relation has already gone through all the checks.

One thing we have to make sure is that orders should have their corresponding addresses not related to back the user addresses. Given this condition what should be the best approach that we can take?

**Comment by oyeb** [comment]
> The tradeoffs with using this approach like not being able to use the DB constraints don't really matter here because the original address in the user relation has already gone through all the checks.

This implies that the user would have to save the address before checkout as she can only associate addresses that have "gone through the validation". What if the user does not want to save this address (see the second "requirement" of this issue)?

> One thing we have to make sure is that orders should have their corresponding addresses not related to back the user addresses.

Isn't this why you want to clone/put embeds in the first place? There's nothing in the embeds that can ever relate back to any user -- just address fields.

1. Is there something called a User address? AFAICS there's only `billing_address` and `shipping_address`.
1. Is there a difference between keeping cloned rows in the Address table and embeds? What do you gain by embedding? Embedding won't make it edit-proof, your `cast()` / `changeset()` will do that.
2. Why shouldn't the user be able to use an address that she hasn't saved? Even if this seems minor, and that we may get away by disallowing it, it still doesn't justify using embeds _and_ losing constraints both.
3. We _already_ know that orders once confirmed are etched into stone, and the same should hold for an associated address. I agree. I'm not editing the "address", only the fact that this address is now no longer associated with a user (aka `user_id` column is being set to `null`). Are you afraid such a function/feature might be abused? How so (it updates a column that has irrelevant info about the "address" **in the context of an order**)?
4. If we go the embeds route, why do we need an Address schema and table? Just for "saved addresses"? Isn't the real utility of an Address in the context of an Order, to compute shipping cost, etc.?

Embedding will work out in the end, but I'd like some critique on the alternative. We should be dead sure about our choices. I'm not convinced by "seems like an overkill", whereas in fact, the alternative is an elegant and efficient solution that is also simple to implement.

**Comment by ashish173** [comment]
As per our last discussion, we'll have **all** the addresses saved in the `address` relation no matter if the user wants to save them or not(throwaway addresses in case of gift orders). 

All these addresses map to the user. 

The addresses(shipping, billing) would also be embedded in the order for the sake of preserving the state of the address at a given time. This should be independent of address relation and not reference back to the `address` relation.

**Comment by kanishkablack** [comment]
> 1. Multiple addresses
> > I am in support of user being able to add multiple addresses. There should be no limits on that.

I agree with it.

My thoughts:

Versioning of address (may not be right title).

```elixir
address_id = %{
   address: "some area"
   area: "area"
   type: "shipping_address || billing addresss "
   state: false
   id: "some uuid"
   user_id: "userid mapping"
 }
```

`address_id` can be used for multiple instances like, billing, shipping or in previous orders.

User can have multiple address stored.

**Comment by ashish173** [comment]
We have addresses sorted now so closing this discussion.
